name: Test Project
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: npm install
        run: npm i
      - name: eslint
        run: npm run lintQuiet
      - name: typescript
        run: npm run typecheck

